import palavasGraph from './palavas.graph'
import palavasHooks from './palavas.hook'
import nigerGraph from './niger.graph'

export default {
  language: 'en',
  thematics: [
    {
      id: 'CLIMATE',
      name: 'Climate',
      color: '#008777',
    },
    {
      id: 'WATER',
      name: 'Water',
      color: '#0082C2',
    },
    {
      id: 'OCEAN',
      name: 'Ocean',
      color: '#004D7E',
    },
    {
      id: 'AIR',
      name: 'Air',
      color: '#8BB7E2',
    },
    {
      id: 'LAND',
      name: 'Land',
      color: '#94C11F',
    },
    {
      id: 'HEALTH',
      name: 'Health',
      color: '#009D45',
    },
    {
      id: 'DISASTER',
      name: 'Natural Disasters',
      color: '#E9483F',
    },
    {
      id: 'FOOD',
      name: 'Food',
      color: '#E0E622',
    },
    {
      id: 'COSTAL',
      name: 'Costal',
      color: '#009679',
    },
  ],
  scenarios: [
    {
      id: 'DISAPPEAR_LAKES',
      thematic: 'FOOD',
      title: 'Disappearance of freshwater lakes',
      abstract: 'The drying up of large lakes is a process of diminishing the surface, volume and water level of large lakes. This drying causes an increase in salinity, which in turn plays a decisive role in the deterioration of fauna and flora. Thses different elements result from problems that directly affect local populations',
      notice: 'This scenario contains <em> several<B> images</B> under</em> GNU copyright. <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Licence Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />Ce(tte) <b>œuvre</b> est mise à disposition selon les termes de la <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Licence Creative Commons Attribution 4.0 International</a>. &copy; IAS',
      image: 'http://placeimg.com/350/200/animals/grayscale',
      initialPOILayerVisibility: true,
      poi: {
        lat: 29.15,
        lon: 116.217,
      },
      centerToDistance: 130000,
      attributes: [
        {
          name: 'Country',
          value: 'China',
        },
        {
          name: 'Description',
          value: 'level water evolution',
        },
        {
          name: 'Surface area',
          value: '5100 Km²',
        },
        {
          name: 'Max length',
          value: '170 km',
        },
        {
          name: 'Avertage depth',
          value: '8.4 m',
        },
        {
          name: 'Max width',
          value: '17 km',
        },
        {
          name: 'Max depth',
          value: '25.1 m',
        },
      ],
      layers: [
        {
          category: 'POYANG',
          type: 'WMS',
          baseUrl: 'http://80.158.6.138/mapserv?map=WMS_POYANG',
          visible: true,
          background: false,
          transparent: true,
          format: 'image/png',
          layers: 'SPOT4,SPOT5,LANDSAT2000',
        },
        {
          category: 'POYANG',
          type: 'WMS',
          baseUrl: 'http://80.158.6.138/mapserv?map=WMS_POYANG',
          visible: true,
          background: false,
          transparent: true,
          format: 'image/png',
          layers: 'SUBMERSION',
          zIndex: 11,
        },
      ],
      maps: [],
      legend: {
        type: 'VERTICAL',
        url: 'http://80.158.6.138/mapserv?map=WMS_POYANG&version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=SUBMERSION&format=image/png&STYLE=default',
        title: 'Yearly Submersion Time',
      },
    },
    {
      id: 'MONT_BLANC',
      thematic: 'CLIMATE',
      title: 'Melting glaciers of Mont Blanc',
      abstract: 'Swiss police say hundreds of bodies of mountaineers who have gone missing in the Alps in the past century could emerge in coming years as global warming forces the country’s glaciers to retreat. Alpine authorities have registered a significant increase in the number of human remains discovered last month, with the body of a man missing for 30 years the most recent to be uncovered. Rescue teams in Saas Valley in the Valais canton were called last Tuesday after two climbers retreating from an aborted ascent spotted a hand and two shoes protruding from the Hohlaub glacier.',
      notice: 'This scenario contains <em> several<B> images</B> under</em> GNU copyright. <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Licence Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />Ce(tte) œuvre est mise à disposition selon les termes de la <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Licence Creative Commons Attribution 4.0 International</a>. &copy; IAS',
      image: 'http://placeimg.com/350/200/people/grayscale',
      initialPOILayerVisibility: true,
      poi: {
        lat: 45.8053,
        lon: 7.0848,
      },
      centerToDistance: 75000,
      resetCameraRotation: {
        heading: -135 / 0.05,
        tilt: -45 / 0.05,
      },
      attributes: [],
      layers: [
        {
          category: 'MONT_BLANC',
          type: 'WMS',
          baseUrl: 'http://80.158.6.138/mapserv?map=WMS_MONT_BLANC',
          layers: 'Mont_Blanc_SHP',
          visible: true,
          background: false,
          transparent: true,
          format: 'image/png',
        },
        {
          category: 'MONT_BLANC',
          type: 'WMS',
          baseUrl: 'http://80.158.6.138/mapserv?map=WMS_MONT_BLANC',
          layers: 'Mont_Blanc_dh',
          visible: true,
          background: false,
          transparent: true,
          format: 'image/png',
          zIndex: 11,
        },
        {
          type: 'WCSElevation',
          name: 'Elevation Mont Blanc',
          baseUrl: 'http://80.158.6.138/mapserv?map=WMS_MONT_BLANC_ELEV',
          coverage: 'MNT_Mont_Blanc',
          version: '1.0.0',
          minElevation: -150,
          scale: 2,
        },
      ],
      maps: [],
      legend: {
        type: 'VERTICAL',
        url: 'http://80.158.6.138/mapserv?map=WMS_MONT_BLANC&service=wms&version=1.1.1&request=getLegendGraphic&layer=Mont_Blanc_dh&format=image/png&STYLE=default&WIDTH=100&%20height=100',
        title: 'Elevation differences in meters between the Pleiades DEM of 2003/08/23 2012/08/19',
      },
    },
    {
      id: 'PALAVAS_COASTLINE',
      thematic: 'COSTAL',
      title: 'Palavas coastline',
      abstract: 'Swiss police say hundreds of bodies of mountaineers who have gone missing in the Alps in the past century could emerge in coming years as global warming forces the country’s glaciers to retreat. Alpine authorities have registered a significant increase in the number of human remains discovered last month, with the body of a man missing for 30 years the most recent to be uncovered. Rescue teams in Saas Valley in the Valais canton were called last Tuesday after two climbers retreating from an aborted ascent spotted a hand and two shoes protruding from the Hohlaub glacier.',
      notice: 'This scenario contains <em> several<B> images</B> under</em> GNU copyright. <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Licence Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />Ce(tte) œuvre est mise à disposition selon les termes de la <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Licence Creative Commons Attribution 4.0 International</a>. &copy; IAS',
      image: 'http://placeimg.com/350/200/nature/grayscale',
      initialPOILayerVisibility: true,
      poi: {
        lat: 43.559,
        lon: 4.037,
      },
      centerToDistance: 39000,
      attributes: [],
      layers: [
        {
          category: 'PALAVAS',
          type: 'WMS',
          baseUrl: 'http://80.158.6.138/mapserv?map=WMS_PALAVAS',
          layers: 'S2_PALAVAS',
          visible: true,
          background: false,
          transparent: true,
          format: 'image/png',
        },
        {
          category: 'PALAVAS',
          type: 'WMS',
          baseUrl: 'http://80.158.6.138/mapserv?map=WMS_PALAVAS',
          layers: 'DEM_PALAVAS',
          visible: true,
          background: false,
          transparent: true,
          format: 'image/png',
          hasParameter: true, //SCO - this layer receive slider parameter value
        },
        {
          category: 'PALAVAS',
          type: 'WMS',
          baseUrl: 'http://80.158.6.138/mapserv?map=WMS_MEDIT',
          visible: false,
          background: false,
          transparent: true,
          format: 'image/png',
          layers: 'Mediterranean',
        },
      ],
      graph: {
        useScenarioDateToSplitData: true,
        splitColor: '#0082C2',
        data: [
          {
            x: palavasGraph.x,
            y: palavasGraph.y,
            type: 'scatter',
            mode: 'lines',
            marker: {
              color: '#9E9E9E',
            },
          },
        ],
        layout: {
          showlegend: false,
          margin: {
            t: 40, r: 20, l: 60, b: 60,
          },
          height: '300',
          title: 'Water elevation variation on Mediterranean Sea',
          autosize: true,
          paper_bgcolor: 'rgba(255,255,255,0.9)',
          plot_bgcolor: 'rgba(255,255,255,0)',
          xaxis: {
            title: 'Date',
          },
          yaxis: {
            title: 'Water elevation in meter',
          },
        },
        config: {
          staticPlot: true,
          displayModeBar: false,
        },
      },
      maps: [],
      parameter: {
        type: 'SLIDER',
        formatValue: value => `${parseFloat(value).toFixed(1)}m`,
        max: 3,
        step: 0.5,
        defaultValue: 0,
        title: 'Additionnal water elevation',
        attrName: 'styles',
      },
      legend: {
        type: 'VERTICAL',
        url: 'http://80.158.6.138/mapserv?map=WMS_PALAVAS&version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=DEM_PALAVAS&format=image/png&STYLE=3.0m',
        title: 'Effect of submersion on Palavas',
      },
      hook: palavasHooks,
    },
    {
      id: 'TROPICAL',
      thematic: 'FOOD',
      title: 'The Niger river basin',
      abstract: 'With a length of 4,200 km, the Niger river is the third longest river in Africa. The active basin is shared by nine African states (Benin, Burkina Faso, Cameroon, Ivory Coast, Guinee, Mali, Niger, Nigeria and Chad) and the river plays a key role in the region in terms of food production. 130 million people live within the Niger Basin and this number must be doubled in the next 50 years.<p> Over the last 15 years, global changes and strong rainfall are causing extreme flooding in Sahel. Niamey the capital city of Niger is suffering repeated damages that are threatening the population’s resilience. The problem is expected to increase with climate change and  population growth.<p><figure><img style="max-width: 100%" src="https://www.dropbox.com/s/topfcw050uqnq9e/niger_discharge.png?raw=1" alt="Niger Discharge"><figcaption>Increase in the Niger river  water levels in Niamey over the years 2010s</figcaption></figure>',
      notice: 'This scenario contains <em> several<B> images</B> under</em> GNU copyright. <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Licence Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />Ce(tte) œuvre est mise à disposition selon les termes de la <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Licence Creative Commons Attribution 4.0 International</a>. &copy; IAS',
      image: 'https://www.dropbox.com/s/1ksqubc7tznleum/niger_scenario.png?raw=1',
      initialPOILayerVisibility: true,
      poi: {
        lat: 13.4551,
        lon: 2.5214,
      },
      centerToDistance: 3000000,
      attributes: [],
      layers: [
        {
          name: 'Niger',
          type: 'WMS',
          baseUrl: 'http://80.158.6.138/mapserv?map=WMS_NIGER',
          layers: 'NIGER_SCENE',
          visible: true,
          transparent: true,
          format: 'image/png',
        },
        {
          category: 'NIGER',
          type: 'WMS',
          baseUrl: 'http://80.158.6.138/mapserv?map=WMS_NIGER',
          layers: 'MEGHA_TRO_GRAY',
          visible: true,
          background: false,
          transparent: true,
          format: 'image/png',
        },
      ],
      maps: [],
      graph: {
        useScenarioDateToSplitData: true,
        splitColor: '#0082C2',
        data: [
          {
            x: nigerGraph.x,
            y: nigerGraph.y,
            type: 'scatter',
            mode: 'lines',
            marker: {
              color: '#9E9E9E',
            },
          },
        ],
        layout: {
          showlegend: false,
          margin: {
            t: 40, r: 20, l: 60, b: 60,
          },
          height: '300',
          title: 'River flow in m³ / seconde',
          autosize: true,
          paper_bgcolor: 'rgba(255,255,255,0.9)',
          plot_bgcolor: 'rgba(255,255,255,0)',
          xaxis: {
            title: 'Date',
          },
          yaxis: {
            title: 'Flow',
          },
        },
        config: {
          staticPlot: true,
          displayModeBar: false,
        },
      },
      legend: {
        type: 'VERTICAL',
        url: 'http://80.158.6.138/mapserv?map=WMS_NIGER&version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=MEGHA_TRO_GRAY&format=image/png&STYLE=default',
        title: 'Daily accumulated surface rainfall in mm/day',
      },
    },
    {
      id: 'MEDITERRANEAN_COASTLINE',
      thematic: 'COSTAL',
      title: 'Mediterranean sea level anomaly',
      abstract: 'Altimeter satellite gridded Sea Level Anomalies (SLA) computed with respect to a twenty-year 2012 mean. The SLA is estimated by Optimal Interpolation, merging the measurement from the different altimeter missions available',
      notice: 'This scenario contains <em> several<B> images</B> under</em> GNU copyright. <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Licence Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />Ce(tte) œuvre est mise à disposition selon les termes de la <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Licence Creative Commons Attribution 4.0 International</a>. &copy; IAS',
      image: 'http://placeimg.com/350/200/animals/grayscale',
      initialPOILayerVisibility: false,
      poi: {
        lat: 39.08,
        lon: 18.5,
      },
      centerToDistance: 3000000,
      attributes: [],
      layers: [
        {
          category: 'MEDITERRANEAN SEA',
          type: 'WMS',
          baseUrl: 'http://80.158.6.138/mapserv?map=WMS_MEDIT',
          layers: 'Mediterranean',
          visible: true,
          background: false,
          transparent: true,
          format: 'image/png',
        },
      ],
      maps: [],
      legend: {
        type: 'VERTICAL',
        url: 'http://80.158.6.138/mapserv?map=WMS_MEDIT&version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=Mediterranean&format=image/png&STYLE=default',
        title: 'Sea Level Anomaly',
      },
    },
  ],
  baseLayers: [
    {
      type: 'WCSElevation',
      name: 'Elevation',
      baseUrl: 'http://80.158.6.138/mapserv?map=WMS_SRTM',
      coverage: 'SRTM',
      version: '1.0.0',
      minElevation: -32000,
      scale: 15,
    },
    {
      name: 'Blue Marble',
      type: 'WMS',
      baseUrl: 'http://80.158.6.138/mapserv?map=WMS_BLUEMARBLE',
      visible: true,
      background: true,
    },
    // {
    //   category: 'Other',
    //   type: 'Atmosphere',
    //   exposure: 2.0,
    //   wavelength: [0.650, 0.570, 0.475],
    //   kr: 0.0025,
    //   km: 0.0015,
    //   sunBrightness: 15.0,
    //   name: 'Atmosphere',
    //   visible: true,
    // },
    {
      category: 'Other',
      type: 'TileWireframe',
      name: 'Coordinates Grid',
      outline: true,
      visible: true,
    },
  ],
}
