import palavasGraph from './palavas.graph'
import palavasHooks from './palavas.hook'
import nigerGraph from './niger.graph'

export default {
  language: 'en',
  thematics: [
    {
      id: 'CLIMATE',
      name: 'Climate',
      color: '#008777',
    },
    {
      id: 'WATER',
      name: 'Water',
      color: '#0082C2',
    },
    {
      id: 'OCEAN',
      name: 'Ocean',
      color: '#004D7E',
    },
    {
      id: 'AIR',
      name: 'Air',
      color: '#8BB7E2',
    },
    {
      id: 'LAND',
      name: 'Land',
      color: '#94C11F',
    },
    {
      id: 'HEALTH',
      name: 'Health',
      color: '#009D45',
    },
    {
      id: 'DISASTER',
      name: 'Natural Disasters',
      color: '#E9483F',
    },
    {
      id: 'FOOD',
      name: 'Food',
      color: '#E0E622',
    },
    {
      id: 'COSTAL',
      name: 'Coastal',
      color: '#009679',
    },
  ],
  scenarios: [
    {
      id: 'MEDITERRANEAN_COASTLINE',
      thematic: 'COSTAL',
      title: 'Global change and local impacts',
      abstract: 'Global warming is causing Earth’s oceans to expand and continental ice, including the polar ice caps, to melt. These processes are fuelling a <b>mean rise in sea level of 3.3 mm a year</b>.<br/><br/>This inexorable rise is having immediate consequences for coasts, like <b>permanent submersion of low-lying coastal areas, more serious storm surge flooding</b> and <b>increasing salinity of aquifers</b>. In the medium to long term, <b>coastal erosion</b> is accelerating, especially on beaches. Another long-term effect is the <b>destruction of ecosystems</b> such as mangroves, coral reefs and maritime marshes, along with <b>the entire socio-economic fabric</b> that depends on them.<br/><br/>These coastal zones are already being subjected to multiple natural or anthropogenic factors, so it’s very hard to predict how they will respond to rising sea level. What’s certain is that water levels are rising and regions are going to have to keep a close eye on shorelines to anticipate the impacts and devise defence strategies.',
      notice: 'Change the time to visualize the sea elevation on the coast',
      image: 'http://80.158.22.249/resources/sco/meditocean/meditSea.png',
      imgCopyright: 'Photo Credit : CNES/LEGOS/CLS 2015 - produced by AVISO',
      initialPOILayerVisibility: false,
      poi: {
        lat: 38.535,
        lon: 14.517,
      },
      centerToDistance: 3045000,
      attributes: [
      ],
      layers: [
        {
          category: 'MEDITERRANEAN SEA',
          type: 'WMS',
          baseUrl: 'https://80.158.22.249/mapserv?map=WMS_MEDIT',
          layers: 'Mediterranean',
          visible: true,
          background: false,
          transparent: true,
          format: 'image/png',
        },
      ],
      maps: [],
      legend: {
        type: 'VERTICAL',
        url: 'https://80.158.22.249/mapserv?map=WMS_MEDIT&version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=Mediterranean&format=image/png&STYLE=default',
        title: 'Sea Level Anomaly',
      },
    },
    {
      id: 'PALAVAS_COASTLINE',
      thematic: 'COSTAL',
      title: 'Palavas-les-Flots under close watch',
      abstract: 'The LEGOS space geophysics and oceanography research laboratory has developed a satellite-based procedure for establishing a coastal vulnerability index. Combining satellite altimetry data and imagery, this procedure translates local topography into a digital terrain model (DTM) and compares it to sea level rise. This approach is able to identify <b>areas that could be submerged</b>. Geodetic satellites are a vital element of the procedure, serving as the reference system required to adjust the topography and sea level.<br/><br/>This satellite-based method was developed for Palavas-les-Flots on France’s Mediterranean coast, chosen as a telltale indicator due to the availability of numerous survey measurements. The objective was to gauge the main risk to coasts from rising sea level: permanent submersion or storm surge flooding.<br/><br/>Submersion depends on the level of the water and land. While the sea level may vary, the shape of the shoreline also changes as a result of currents and coastal engineering. The threat of flooding increases in the event of a storm, as low pressures, winds, waves and swell combine to wreak havoc. And if combined with heavy rainfall in a neighbouring drainage basin, rivers may burst their banks and the area is subjected to flooding from both sea and land.',
      notice: 'Change the sea anomaly and the time to visualize the impact on Palavas-les-Flots.',
      image: 'http://80.158.22.249/resources/sco/palavas/palavas.png',
      imgCopyright: 'Photo Credit : CNES 2013, distribution Airbus DS',
      initialPOILayerVisibility: true,
      poi: {
        lat: 43.556,
        lon: 4.018,
      },
      centerToDistance: 35000,
      attributes: [
      ],
      layers: [
        {
          category: 'PALAVAS',
          type: 'WMS',
          baseUrl: 'https://80.158.22.249/mapserv?map=WMS_PALAVAS',
          layers: 'S2_PALAVAS',
          visible: true,
          background: false,
          transparent: true,
          format: 'image/png',
        },
        {
          category: 'PALAVAS',
          type: 'WMS',
          baseUrl: 'https://80.158.22.249/mapserv?map=WMS_PALAVAS',
          layers: 'DEM_PALAVAS',
          visible: true,
          background: false,
          transparent: true,
          format: 'image/png',
          hasParameter: true, //SCO - this layer receive slider parameter value
        },
        {
          category: 'PALAVAS',
          type: 'WMS',
          baseUrl: 'https://80.158.22.249/mapserv?map=WMS_MEDIT',
          visible: false,
          background: false,
          transparent: true,
          format: 'image/png',
          layers: 'Mediterranean',
        },
      ],
      graph: {
        useScenarioDateToSplitData: true,
        splitColor: '#0082C2',
        data: [
          {
            x: palavasGraph.x,
            y: palavasGraph.y,
            type: 'scatter',
            mode: 'lines',
            marker: {
              color: '#9E9E9E',
            },
          },
        ],
        layout: {
          showlegend: false,
          margin: {
            t: 40, r: 20, l: 60, b: 60,
          },
          height: '300',
          title: 'Water elevation variation',
          autosize: true,
          paper_bgcolor: 'rgba(255,255,255,0.9)',
          plot_bgcolor: 'rgba(255,255,255,0)',
          xaxis: {
            title: 'Date',
          },
          yaxis: {
            title: 'Water elevation in meter',
          },
        },
        config: {
          staticPlot: true,
          displayModeBar: false,
        },
      },
      maps: [],
      parameter: {
        type: 'SLIDER',
        formatValue: value => `${parseFloat(value).toFixed(1)}m`,
        max: 3,
        step: 0.2,
        defaultValue: 0,
        title: 'Additionnal water elevation',
        attrName: 'styles',
      },
      legend: {
        type: 'VERTICAL',
        url: 'https://80.158.22.249/mapserv?map=WMS_PALAVAS&version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=DEM_PALAVAS&format=image/png&STYLE=3.0m',
        title: 'Effect of submersion on Palavas',
      },
      hook: palavasHooks,
    },
    {
      id: 'TROPICAL',
      thematic: 'FOOD',
      title: 'All water paths lead to Niamey',
      abstract: 'Dry in the north and heavily watered in the south, the Niger watershed is the nurturing source of 9 countries, a <b>population of 130 million</b>, expected <b>to double in the next 50 years</b>. Niamey, which is not an isolated case, is suffering the <b>consequences of climate change</b>: the <b>severe droughts</b> of the 1970s and 1980s and erratic rainfall since 1990 have modified the hydrological behavior of the region. With climate change the <b>rains could intensify</b> and further aggravate these phenomena as the urban population believes. From now on, at the slightest rain in the Niamey region, Niger is flooding in the capital.',
      notice: 'Change the time to see the rainfall in the Niger basin and the impact on the flood wave that arrives in Niamey.',
      image: 'http://80.158.22.249/resources/sco/niger/RCSA_08_35_Rue_inondee_voitures_Ouaga_Hubert_Bataille.png',
      imgCopyright: 'Photo Credit : Hubert Bataille',
      initialPOILayerVisibility: true,
      poi: {
        lat: 15.261,
        lon: 4.245,
      },
      centerToDistance: 3940000,
      attributes: [
      ],
      layers: [
        {
          name: 'Niger',
          type: 'WMS',
          baseUrl: 'https://80.158.22.249/mapserv?map=WMS_NIGER',
          layers: 'NIGER_SCENE',
          visible: true,
          transparent: true,
          format: 'image/png',
        },
        {
          category: 'NIGER',
          type: 'WMS',
          baseUrl: 'https://80.158.22.249/mapserv?map=WMS_NIGER',
          layers: 'MEGHA_TRO_GRAY',
          visible: true,
          background: false,
          transparent: true,
          format: 'image/png',
        },
      ],
      //overrideTemporalDates: [new Date(2014, 6, 1), new Date(2015, 6, 1), new Date(2016, 6, 1), new Date(2017, 6, 1)],
      maps: [],
      graph: {
        useScenarioDateToSplitData: true,
        splitColor: '#0082C2',
        data: [
          {
            x: nigerGraph.x,
            y: nigerGraph.y,
            type: 'scatter',
            mode: 'lines',
            marker: {
              color: '#9E9E9E',
            },
          },
        ],
        layout: {
          showlegend: false,
          margin: {
            t: 40, r: 20, l: 60, b: 60,
          },
          height: '300',
          title: 'River flow in m³ / seconde',
          autosize: true,
          paper_bgcolor: 'rgba(255,255,255,0.9)',
          plot_bgcolor: 'rgba(255,255,255,0)',
          xaxis: {
            title: 'Date',
          },
          yaxis: {
            title: 'Flow',
          },
        },
        config: {
          staticPlot: true,
          displayModeBar: false,
        },
      },
      legend: {
        type: 'VERTICAL',
        url: 'https://80.158.22.249/mapserv?map=WMS_NIGER&version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=MEGHA_TRO_GRAY&format=image/png&STYLE=default',
        title: 'Daily accumulated surface rainfall in mm/day',
      },
    },
    {
      id: 'MONT_BLANC',
      thematic: 'CLIMATE',
      title: 'The altitude loss of Mont-Blanc',
      abstract: 'In the French Alps, the <b>Mont-Blanc massif has lost at least 40% of its glaciers in 150 years</b>. Satellites are now providing more precise measurements across the entire mountain range. What these measurements show is that with a mean loss of thickness of more than one metre a year, the Mont-Blanc’s glaciers are melting three to four times faster in the current decade than in the two previous decades.',
      notice: 'Change the time and visualize the changes in altitude of Mont Blanc between 2003 and 2012.',
      image: 'http://80.158.22.249/resources/sco/montblanc/Mont-blanc.jpg',
      imgCopyright: 'Photo Credit : E. Berthier',
      initialPOILayerVisibility: true,
      poi: {
        lat: 45.8053,
        lon: 7.0848,
      },
      centerToDistance: 75000,
      resetCameraRotation: {
        heading: 200,
        tilt: 45,
      },
      attributes: [
      ],
      layers: [
        {
          category: 'MONT_BLANC',
          type: 'WMS',
          baseUrl: 'https://80.158.22.249/mapserv?map=WMS_MONT_BLANC',
          layers: 'Mont_Blanc_SHP',
          visible: true,
          background: false,
          transparent: true,
          format: 'image/png',
        },
        {
          category: 'MONT_BLANC',
          type: 'WMS',
          baseUrl: 'https://80.158.22.249/mapserv?map=WMS_MONT_BLANC',
          layers: 'Mont_Blanc_dh',
          visible: true,
          background: false,
          transparent: true,
          format: 'image/png',
          zIndex: 11,
        },
        {
          type: 'WCSElevation',
          name: 'Elevation Mont Blanc',
          baseUrl: 'https://80.158.22.249/mapserv?map=WMS_MONT_BLANC_ELEV',
          coverage: 'MNT_Mont_Blanc',
          version: '1.0.0',
          scale: 2,
          attribution: '<img src="http://80.158.22.249/resources/sco/logos/logo-cnes.jpg" height="25px"/> &copy; Data: CNES 2003, 2012 / Distribution Airbus and Space / Processing E. Berthier, Legos / Web service: CNES</a>',
        },
      ],
      maps: [],
      legend: {
        type: 'VERTICAL',
        url: 'https://80.158.22.249/mapserv?map=WMS_MONT_BLANC&service=wms&version=1.1.1&request=getLegendGraphic&layer=Mont_Blanc_dh&format=image/png&STYLE=default&WIDTH=100&%20height=100',
        title: 'Elevation differences after 9 years in meter between the two Digital Elevation Models',
      },
    },
    {
      id: 'DISAPPEAR_LAKES',
      thematic: 'FOOD',
      title: 'Disappearance of freshwater lakes',
      abstract: 'The drying up of large lakes is a process of diminishing the surface, volume and water level of large lakes. This drying causes an increase in salinity, which in turn plays a decisive role in the deterioration of fauna and flora. Thses different elements result from problems that directly affect local populations',
      image: 'http://80.158.22.249/resources/sco/poyang/poyang.png',
      imgCopyright: 'Photo Credit : Deimos Imaging, an UrtheCast Company, Distribution Airbus DS, 2010',
      initialPOILayerVisibility: true,
      poi: {
        lat: 29.648,
        lon: 116.685,
      },
      centerToDistance: 667000,
      attributes: [
      ],
      layers: [
        {
          category: 'POYANG',
          type: 'WMS',
          baseUrl: 'https://80.158.22.249/mapserv?map=WMS_POYANG',
          visible: true,
          background: false,
          transparent: true,
          format: 'image/png',
          layers: 'SPOT4,SPOT5,LANDSAT2000',
        },
        {
          category: 'POYANG',
          type: 'WMS',
          baseUrl: 'https://80.158.22.249/mapserv?map=WMS_POYANG',
          visible: true,
          background: false,
          transparent: true,
          format: 'image/png',
          layers: 'SUBMERSION',
          zIndex: 11,
        },
      ],
      maps: [],
      legend: {
        type: 'VERTICAL',
        url: 'https://80.158.22.249/mapserv?map=WMS_POYANG&version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=SUBMERSION&format=image/png&STYLE=default',
        title: 'Yearly Submersion Time',
      },
    },
    {
      id: 'INDIAN_MOISTURE',
      thematic: 'FOOD',
      title: 'Anticipating the agronomic drought of India',
      abstract: 'India has a <b>population of 1.3 billion</b> living within a total area of <b>3.3 million sq.km.</b> Farmlands occupy some 60% of this area and consume <b>80% of the nation’s water resources</b>, which come mostly from groundwater. As droughts intensify, overabstraction is such that groundwater reserves have reached the point where they are no longer being replenished in several states. Not only a source of tension but also a financial black hole for insurers, <b>the water deficit</b> is proving dramatic for farmers. In response, the Indian government is building additional reservoirs and seeking to identify actions capable of mitigating or coping with dwindling resources. In particular, it is stepping up cooperation with France to develop space-based tools designed to inform choices and decisions.',
      image: 'http://80.158.22.249/resources/sco/india/22040610056_fca942e9a4_o.jpg',
      imgCopyright: 'Photo Credit : A. Al Bitar',
      initialPOILayerVisibility: false,
      poi: {
        lat: 22.696,
        lon: 81.160,
      },
      centerToDistance: 4035000,
      attributes: [
      ],
      layers: [
        {
          category: 'INDIA',
          type: 'WMS',
          baseUrl: 'https://80.158.22.249/mapserv?map=WMS_INDIA',
          layers: 'INDIA_ADMIN',
          visible: true,
          background: false,
          transparent: true,
          format: 'image/png',
          zIndex: 11,
        },
        {
          category: 'INDIA',
          type: 'WMS',
          baseUrl: 'https://80.158.22.249/mapserv?map=WMS_INDIA',
          layers: 'MoistureIndex',
          visible: true,
          background: false,
          transparent: true,
          format: 'image/png',
        },
      ],
      maps: [],
      legend: {
        type: 'VERTICAL',
        url: 'https://80.158.22.249/mapserv?map=WMS_INDIA&version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=MoistureIndex&format=image/png&STYLE=default',
        title: 'Indice d\'humidité du sol en surface',
      },
    },
  ],
  baseLayers: [
    {
      type: 'WCSElevation',
      name: 'Elevation',
      baseUrl: 'https://80.158.22.249/mapserv?map=WMS_SRTM',
      coverage: 'SRTM',
      version: '1.0.0',
      minElevation: -32000,
      scale: 2,
      attribution: '<img src="https://visibleearth.nasa.gov/siteimages/nasa_logo.png" height="25px"/> <a href="https://lta.cr.usgs.gov/srtm/data_distribution_policy">&copy; Data: NASA-NGA partnership / Web service : CNES</a>',
    },
    {
      name: 'Blue Marble',
      type: 'WMS',
      baseUrl: 'https://80.158.22.249/mapserv?map=WMS_BLUEMARBLE',
      visible: true,
      background: true,
    },
    // {
    //   category: 'Other',
    //   type: 'Atmosphere',
    //   exposure: 2.0,
    //   wavelength: [0.650, 0.570, 0.475],
    //   kr: 0.0025,
    //   km: 0.0015,
    //   sunBrightness: 15.0,
    //   name: 'Atmosphere',
    //   visible: true,
    // },
    {
      category: 'Other',
      type: 'TileWireframe',
      name: 'Coordinates Grid',
      outline: true,
      visible: true,
      attribution: '<img src="http://80.158.22.249/resources/sco/logos/mizar.png" height="25px"/> <a href="https://github.com/MizarWeb/Mizar">&copy; MIZAR</a>',
    },
  ],
}
