import palavasGraph from './palavas.graph'
import palavasHooks from './palavas.hook'
import nigerGraph from './niger.graph'

export default {
  language: 'en',
  thematics: [
    {
      id: 'CLIMATE',
      name: 'Climate',
      color: '#008777',
    },
    {
      id: 'WATER',
      name: 'Water',
      color: '#0082C2',
    },
    {
      id: 'OCEAN',
      name: 'Ocean',
      color: '#004D7E',
    },
    {
      id: 'AIR',
      name: 'Air',
      color: '#8BB7E2',
    },
    {
      id: 'LAND',
      name: 'Land',
      color: '#94C11F',
    },
    {
      id: 'HEALTH',
      name: 'Health',
      color: '#009D45',
    },
    {
      id: 'DISASTER',
      name: 'Natural Disasters',
      color: '#E9483F',
    },
    {
      id: 'FOOD',
      name: 'Food',
      color: '#E0E622',
    },
    {
      id: 'COSTAL',
      name: 'Costal',
      color: '#009679',
    },
  ],
  scenarios: [
    {
      id: 'MEDITERRANEAN_COASTLINE',
      thematic: 'COSTAL',
      title: 'Du changement global aux impacts locaux',
      abstract: 'En accélération, la hausse du niveau des mers menace les régions côtières partout dans le monde. Seule une méthode satellitaire permet d’évaluer la vulnérabilité de chaque portion de littoral, une dynamique complexe de phénomènes mondiaux et locaux. Le réchauffement climatique provoque simultanément la dilatation des océans et la fonte des glaces continentales (i.e. calottes polaires, glaciers de montagne). Il en résulte une hausse moyenne de 3,3 mm par an du niveau des océans. Cette crue inexorable a des conséquences immédiates sur les littoraux comme la submersion permanente des côtes basses, une submersion plus importante lors des tempêtes et la salinisation des aquifères. Elle a aussi des conséquences à moyen et long terme comme, l’érosion accélérée des côtes qui est particulièrement visible sur les plages. Une dune protectrice aujourd’hui ne le sera peut-être plus dans quelques années. Une autre conséquence à long terme est la destruction d’ écosystèmes tels que mangroves, récifs coralliens et marais maritimes, qui s’accompagne aussi de la destruction du tissu socio-économie qui en dépend. En plus de la hausse du niveau de la mer, les zones littorales sont soumises à l’influence de multiples phénomènes locaux d’origine naturelle tel que la houle, le vent, ou d’origine anthropique tel que le dragage ou l’aménagement des plages et des zones portuaires. Il est très difficile de prevoir comment ces zones littorales vont réagir à la hausse du niveau de la mer. Ce qui est sûr, c’est que l’eau monte, et les régions doivent aujourd’hui surveiller l’évolution du trait de côte afin d’anticiper les impacts associés et établir une stratégie de défense.',
      notice: 'Fais varier le temps pour visualiser l\'élévation du niveau de l\'eau en Midterranée.',
      image: 'http://80.158.22.249/resources/sco/meditocean/meditSea.png',
      imgCopyright: 'Crédit Photo : CNES/LEGOS/CLS 2015 - produced by AVISO',
      initialPOILayerVisibility: false,
      poi: {
        lat: 38.535,
        lon: 14.517,
      },
      centerToDistance: 3045000,
      attributes: [
      ],
      layers: [
        {
          category: 'MEDITERRANEAN SEA',
          type: 'WMS',
          baseUrl: 'http://80.158.22.249/mapserv?map=WMS_MEDIT',
          layers: 'Mediterranean',
          visible: true,
          background: false,
          transparent: true,
          format: 'image/png',
        },
      ],
      maps: [],
      legend: {
        type: 'VERTICAL',
        url: 'http://80.158.22.249/mapserv?map=WMS_MEDIT&version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=Mediterranean&format=image/png&STYLE=default',
        title: 'Sea Level Anomaly',
      },
    },
    {
      id: 'PALAVAS_COASTLINE',
      thematic: 'COSTAL',
      title: 'Palavas-les-Flots sous surveillance',
      abstract: 'Développée par le LegosLEGOS, une procédure spatiale permet d’évaluer un indice de la vulnérabilité des côtes. Combinant les données de satellites d’altimétrie et d’imagerie spatiale, il traduit la topographie locale d’une zone sur un modèle numérique de terrain (MNT) et compare cette topographie à la hausse du niveau de la mer. Cette approche permet d’identifier les zones potentiellement soumises aux submersions permanentes ou occasionelles (lors des tempetes) à cause de la hausse du niveau de la mer. Cette méthode spatiale a été développée sur Palavas-les-Flots (sud-est de la France), choisie comme zone témoin en raison de ses nombreuses mesures de terrain. L\'Objectif est d\'évaluer le premier risque de la hausse des océans : la submersion, permanente ou lors des tempêtes. La submersion dépend du niveau de l\'eau et du niveau du sol. Or, la forme de la côte change, modelée par les courants et l’ingénierie côtière, tout comme la mer varie. La menace de submersion s’accroît lorsqu’une tempête arrive. Tout entre alors en conjonction et avec force : dépression, vents, vagues et houle… S’il pleut trop sur un bassin versant voisin, des crues locales sont à craindre : la zone est prise en tenaille entre débordements salés et non salés.',
      notice: 'Fait varier la hauteur de l\'eau et le temps pour visualiser l\'impact sur Palavas-les-Flots',
      image: 'http://80.158.22.249/resources/sco/palavas/palavas.png',
      imgCopyright: 'Crédit Photo : TODO',
      initialPOILayerVisibility: true,
      poi: {
        lat: 43.556,
        lon: 4.018,
      },
      centerToDistance: 35000,
      attributes: [
      ],
      layers: [
        {
          category: 'PALAVAS',
          type: 'WMS',
          baseUrl: 'http://80.158.22.249/mapserv?map=WMS_PALAVAS',
          layers: 'S2_PALAVAS',
          visible: true,
          background: false,
          transparent: true,
          format: 'image/png',
        },
        {
          category: 'PALAVAS',
          type: 'WMS',
          baseUrl: 'http://80.158.22.249/mapserv?map=WMS_PALAVAS',
          layers: 'DEM_PALAVAS',
          visible: true,
          background: false,
          transparent: true,
          format: 'image/png',
          hasParameter: true, //SCO - this layer receive slider parameter value
        },
        {
          category: 'PALAVAS',
          type: 'WMS',
          baseUrl: 'http://80.158.22.249/mapserv?map=WMS_MEDIT',
          visible: false,
          background: false,
          transparent: true,
          format: 'image/png',
          layers: 'Mediterranean',
        },
      ],
      graph: {
        useScenarioDateToSplitData: true,
        splitColor: '#0082C2',
        data: [
          {
            x: palavasGraph.x,
            y: palavasGraph.y,
            type: 'scatter',
            mode: 'lines',
            marker: {
              color: '#9E9E9E',
            },
          },
        ],
        layout: {
          showlegend: false,
          margin: {
            t: 40, r: 20, l: 60, b: 60,
          },
          height: '300',
          title: 'Water elevation variation on Mediterranean Sea',
          autosize: true,
          paper_bgcolor: 'rgba(255,255,255,0.9)',
          plot_bgcolor: 'rgba(255,255,255,0)',
          xaxis: {
            title: 'Date',
          },
          yaxis: {
            title: 'Water elevation in meter',
          },
        },
        config: {
          staticPlot: true,
          displayModeBar: false,
        },
      },
      maps: [],
      parameter: {
        type: 'SLIDER',
        formatValue: value => `${parseFloat(value).toFixed(1)}m`,
        max: 3,
        step: 0.2,
        defaultValue: 0,
        title: 'Additionnal water elevation',
        attrName: 'styles',
      },
      legend: {
        type: 'VERTICAL',
        url: 'http://80.158.22.249/mapserv?map=WMS_PALAVAS&version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=DEM_PALAVAS&format=image/png&STYLE=3.0m',
        title: 'Effect of submersion on Palavas',
      },
      hook: palavasHooks,
    },
    {
      id: 'TROPICAL',
      thematic: 'FOOD',
      title: 'UNE RECRUSDESCENCE DES INONDATIONS',
      abstract: 'Très sensible au changement climatique, la ceinture tropicale connaît une météo et une hydrologie chahutées à l’extrême. Depuis environ 15 ans, alors même que les pluies reprennent enfin après deux décennies de sécheresse, tout en s’intensifiant, elles causent des inondations dévastatrices : conséquence des sécheresses étendues des années précédentes, les sols encroûtés laissent ruisseler plus d’eau vers les rivières, qui entrent en crue. Niamey, Bamako, Dakar ou encore Ouagadougou, la population des grandes villes, dense et majoritairement pauvre, est durement frappée par de violentes inondations. Habitats, cultures et cheptels détruits mettent en péril la sécurité alimentaire.<br><br><b>Suivre la pluie et prédire les crues</b><br>Sec au nord, très arrosé au sud, le bassin versant du Niger est le site pilote d’utilisation des données spatiales pour les thématiques liées à l’eau. Coopération internationale, ce démonstrateur sollicite la constellation internationale GPM, Global Precipitation Measurement. Parmi ses 10 satellites, Megha-Tropiques observe uniquement les tropiques, 5 à 6 fois par jour. Cette fréquence est nécessaire pour analyser des systèmes pluvieux particulièrement variables dans les tropiques, avec des pluies aussi soudaines qu’intenses.',
      notice: 'Fais varier le temps pour visualiser les précipitations sur le bassin du Niger et l\'impact sur le débit du fleuve.',
      image: 'http://80.158.22.249/resources/sco/niger/RCSA_08_35_Rue_inondee_voitures_Ouaga_Hubert_Bataille.png',
      imgCopyright: 'Crédit Photo : Hubert Bataille',
      initialPOILayerVisibility: true,
      poi: {
        lat: 15.261,
        lon: 4.245,
      },
      centerToDistance: 3940000,
      attributes: [
      ],
      layers: [
        {
          name: 'Niger',
          type: 'WMS',
          baseUrl: 'http://80.158.22.249/mapserv?map=WMS_NIGER',
          layers: 'NIGER_SCENE',
          visible: true,
          transparent: true,
          format: 'image/png',
        },
        {
          category: 'NIGER',
          type: 'WMS',
          baseUrl: 'http://80.158.22.249/mapserv?map=WMS_NIGER',
          layers: 'MEGHA_TRO_GRAY',
          visible: true,
          background: false,
          transparent: true,
          format: 'image/png',
        },
      ],
      maps: [],
      graph: {
        useScenarioDateToSplitData: true,
        splitColor: '#0082C2',
        data: [
          {
            x: nigerGraph.x,
            y: nigerGraph.y,
            type: 'scatter',
            mode: 'lines',
            marker: {
              color: '#9E9E9E',
            },
          },
        ],
        layout: {
          showlegend: false,
          margin: {
            t: 40, r: 20, l: 60, b: 60,
          },
          height: '300',
          title: 'River flow in m³ / seconde',
          autosize: true,
          paper_bgcolor: 'rgba(255,255,255,0.9)',
          plot_bgcolor: 'rgba(255,255,255,0)',
          xaxis: {
            title: 'Date',
          },
          yaxis: {
            title: 'Flow',
          },
        },
        config: {
          staticPlot: true,
          displayModeBar: false,
        },
      },
      legend: {
        type: 'VERTICAL',
        url: 'http://80.158.22.249/mapserv?map=WMS_NIGER&version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=MEGHA_TRO_GRAY&format=image/png&STYLE=default',
        title: 'Daily accumulated surfacemois rainfall in mm/day',
      },
    },
    {
      id: 'MONT_BLANC',
      thematic: 'CLIMATE',
      title: 'La perte d\'altitude du Mont-Blanc',
      abstract: 'Aux premi&egrave;res loges du r&eacute;chauffement climatique, la fonte des glaciers engendre des ph&eacute;nom&egrave;nes importants comme les crues de rivi&egrave;re et l&rsquo;&eacute;l&eacute;vation du niveau de la mer. Dans les zones arides comme le P&eacute;rou et le Pakistan, les glaciers jouent le r&ocirc;le de ch&acirc;teau d&rsquo;eau naturel. Stockant l&rsquo;eau durant l&rsquo;hiver, ils la lib&egrave;rent &agrave; la saison s&egrave;che, lorsque l&rsquo;homme et l&rsquo;environnement en ont le plus besoin. Face aux enjeux environnementaux et humains de cette fonte rapide, estimer et suivre les variations des glaciers est devenu indispensable. Une des meilleures fa&ccedil;ons d&rsquo;&eacute;valuer l&rsquo;&eacute;tat de sant&eacute; d&rsquo;un glacier consiste &agrave; suivre sa topographie : si les altitudes baissent, le glacier fond.',
      notice: 'D&eacute;place toi dans le temps et visualise la variation d\'altitude du Mont-Blanc entre 2003 et 2012.',
      image: 'http://80.158.22.249/resources/sco/montblanc/Mont-blanc.jpg',
      imgCopyright: 'Crédit Photo : E. Berthier',
      initialPOILayerVisibility: true,
      poi: {
        lat: 45.8053,
        lon: 7.0848,
      },
      centerToDistance: 75000,
      resetCameraRotation: {
        heading: -135 / 0.05,
        tilt: -45 / 0.05,
      },
      attributes: [
      ],
      layers: [
        {
          category: 'MONT_BLANC',
          type: 'WMS',
          baseUrl: 'http://80.158.22.249/mapserv?map=WMS_MONT_BLANC',
          layers: 'Mont_Blanc_SHP',
          visible: true,
          background: false,
          transparent: true,
          format: 'image/png',
        },
        {
          category: 'MONT_BLANC',
          type: 'WMS',
          baseUrl: 'http://80.158.22.249/mapserv?map=WMS_MONT_BLANC',
          layers: 'Mont_Blanc_dh',
          visible: true,
          background: false,
          transparent: true,
          format: 'image/png',
          zIndex: 11,
        },
        {
          type: 'WCSElevation',
          name: 'Elevation Mont Blanc',
          baseUrl: 'http://80.158.22.249/mapserv?map=WMS_MONT_BLANC_ELEV',
          coverage: 'MNT_Mont_Blanc',
          version: '1.0.0',
          scale: 2,
        },
      ],
      maps: [],
      legend: {
        type: 'VERTICAL',
        url: 'http://80.158.22.249/mapserv?map=WMS_MONT_BLANC&service=wms&version=1.1.1&request=getLegendGraphic&layer=Mont_Blanc_dh&format=image/png&STYLE=default&WIDTH=100&%20height=100',
        title: 'Elevation differences in meter between the Pleiades DEM of 2003/08/23 2012/08/19',
      },
    },
    {
      id: 'DISAPPEAR_LAKES',
      thematic: 'FOOD',
      title: 'Disappearance of freshwater lakes',
      abstract: 'The drying up of large lakes is a process of diminishing the surface, volume and water level of large lakes. This drying causes an increase in salinity, which in turn plays a decisive role in the deterioration of fauna and flora. Thses different elements result from problems that directly affect local populations',
      image: 'http://placeimg.com/350/200/animals/grayscale',
      imgCopyright: 'Crédit Photo  TODO',
      initialPOILayerVisibility: true,
      poi: {
        lat: 29.648,
        lon: 116.685,
      },
      centerToDistance: 667000,
      attributes: [
        {
          name: 'Country',
          value: 'China',
        },
        {
          name: 'Description',
          value: 'level water evolution',
        },
        {
          name: 'Surface area',
          value: '5100 Km²',
        },
        {
          name: 'Max length',
          value: '170 km',
        },
        {
          name: 'Avertage depth',
          value: '8.4 m',
        },
        {
          name: 'Max width',
          value: '17 km',
        },
        {
          name: 'Max depth',
          value: '25.1 m',
        },
      ],
      layers: [
        {
          category: 'POYANG',
          type: 'WMS',
          baseUrl: 'http://80.158.22.249/mapserv?map=WMS_POYANG',
          visible: true,
          background: false,
          transparent: true,
          format: 'image/png',
          layers: 'SPOT4,SPOT5,LANDSAT2000',
        },
        {
          category: 'POYANG',
          type: 'WMS',
          baseUrl: 'http://80.158.22.249/mapserv?map=WMS_POYANG',
          visible: true,
          background: false,
          transparent: true,
          format: 'image/png',
          layers: 'SUBMERSION',
          zIndex: 11,
        },
      ],
      maps: [],
      legend: {
        type: 'VERTICAL',
        url: 'http://80.158.22.249/mapserv?map=WMS_POYANG&version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=SUBMERSION&format=image/png&STYLE=default',
        title: 'Yearly Submersion Time',
      },
    },
    {
      id: 'INDIAN_MOISTURE',
      thematic: 'FOOD',
      title: 'Surveiller l\'eau et la sécheresse',
      abstract: 'Quand le sol a soif, la vie m&ecirc;me est menac&eacute;e. En Inde, 3 satellites luttent contre la s&eacute;cheresse &agrave; toutes ses &eacute;chelles.Le probl&egrave;me du d&eacute;ficit d&rsquo;eau impose et implique diverses d&eacute;cisions des diff&eacute;rents acteurs. Compl&egrave;te, la solution d&eacute;velopp&eacute;e par le CESBIO (Centre d&rsquo;&eacute;tudes spatiales de l&rsquo;atmosph&egrave;re) d&eacute;livre des indicateurs de s&eacute;cheresse &agrave; 3 &eacute;chelles gr&acirc;ce aux potentiels combin&eacute;s de 3 satellites. &laquo; Disaster risk management linked to water ressources is in top prority for Karnataka state, it is linked to major economic and societal issues. &raquo; Karnataka State Disaster Monitoring Center',
      notice: 'TODO',
      image: 'http://80.158.22.249/resources/sco/india/22040610056_fca942e9a4_o.jpg',
      imgCopyright: 'Crédit Photo : A. Al Bitar',
      initialPOILayerVisibility: false,
      poi: {
        lat: 22.696,
        lon: 81.160,
      },
      centerToDistance: 4035000,
      attributes: [
      ],
      layers: [
        {
          category: 'INDIA',
          type: 'WMS',
          baseUrl: 'http://80.158.22.249/mapserv?map=WMS_INDIA',
          layers: 'INDIA_ADMIN',
          visible: true,
          background: false,
          transparent: true,
          format: 'image/png',
          zIndex: 11,
        },
        {
          category: 'INDIA',
          type: 'WMS',
          baseUrl: 'http://80.158.22.249/mapserv?map=WMS_INDIA',
          layers: 'MoistureIndex',
          visible: true,
          background: false,
          transparent: true,
          format: 'image/png',
        },
      ],
      maps: [],
      legend: {
        type: 'VERTICAL',
        url: 'http://80.158.22.249/mapserv?map=WMS_INDIA&version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=MoistureIndex&format=image/png&STYLE=default',
        title: 'Surface Sol Moisture Index',
      },
    },
  ],
  baseLayers: [
    {
      type: 'WCSElevation',
      name: 'Elevation',
      baseUrl: 'http://80.158.22.249/mapserv?map=WMS_SRTM',
      coverage: 'SRTM',
      version: '1.0.0',
      minElevation: -32000,
      scale: 2,
    },
    {
      name: 'Blue Marble',
      type: 'WMS',
      baseUrl: 'http://80.158.22.249/mapserv?map=WMS_BLUEMARBLE',
      visible: true,
      background: true,
    },
    // {
    //   category: 'Other',
    //   type: 'Atmosphere',
    //   exposure: 2.0,
    //   wavelength: [0.650, 0.570, 0.475],
    //   kr: 0.0025,
    //   km: 0.0015,
    //   sunBrightness: 15.0,
    //   name: 'Atmosphere',
    //   visible: true,
    // },
    {
      category: 'Other',
      type: 'TileWireframe',
      name: 'Coordinates Grid',
      outline: true,
      visible: true,
    },
  ],
}
